# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Rohan's Blog
description: I am a programmer passionate about AI and a book reader.
github_username: MrAI-Rohan

# Email and twitter are optional:
email: rohanlalwani@gmail.com
twitter_username: MrAI_Rohan
instagram_username: mr.ai_rohan
rss: https://rss.app/feeds/MUQJ0oHTMOxUWsDu.xml

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: 292290684

# Everything below here can be ignored, unless you want to change the theme entirely
future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
